
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  engine: "classic",
  datasource: {
    // `prisma generate` doesn't need a live connection — avoid Prisma's env()
    // helper here since it throws when the var isn't set yet (e.g. during
    // Vercel's postinstall step, before env vars are fully available).
    url: process.env.DATABASE_URL ?? "",
  },
});
